### ISSUE TITLE
ERROR: Waffle with Spring Boot using Java 9

### ISSUE THREAD

**Issue by patelmitul** [Waffle/waffle#592] opened 2018-02-28 18:24 UTC
The SSO does not work if I use Java 9. It works under Java 8. I've tried both 1.8.3 and 1.9 by compiling master as of Feb 27, 2018. I am attaching my POM, dependency tree, and tomcat error log. 
[Tomcat Error Log](https://github.com/Waffle/waffle/files/1768345/TomcatErrorLog.txt)
[Dependency Tree](https://github.com/Waffle/waffle/files/1768346/tree.txt)
[POM](https://github.com/Waffle/waffle/files/1768347/pom.txt)

I do not know, if I need to start using Spring Boot 2.0. On there site they have noted that they have no plans to support Java 9 under 1.5.x In that case I'll have to wait till Waffle switches to Spring Boot 2.0 too.

**Comment by hazendaz** [comment] 2018-03-03 06:56
Seems like it needs a different jna library.  Since that seems core to the error, have you checked on that project to see if they have issues.  I know the latest last I looked was 4.5.1 so maybe try dropping that one in to see if it helps.

**Comment by patelmitul** [comment] 2018-03-05 14:00
I've specified JNA version 4.5.0 in my POM and verified that in dependency tree. So the core JNA and JNA-Platform are both 4.5.0 and they suppose to work but there sims some more problems beyond that which I don't understand.

**Comment by hazendaz** [comment] 2018-03-08 01:10
Search through our issues on springboot.  There is special consideration for jna but it does work.  There might also be a FAQ on it but not entirely sure there.  

Jna by itself I've confirmed works fine at 4.5.0 and waffle 1.8.3.

**Comment by hazendaz** [comment] 2020-01-09 03:17
Closing as no longer an issue.  Waffle has been tested successfully through jdk 13 on live code.

**Closed by hazendaz** 2020-01-09 03:17 UTC
