### ISSUE TITLE
waffle-negotiate not working with spring boot

### ISSUE THREAD

**Issue by bishnu-zwayam** [Waffle/waffle#460] opened 2016-12-21 17:30 UTC
I tried waffle negotiate but  with spring boot jar, Httpservletrequest remote user returning null.
But if i deploy it in tomcat server as a war file it is returning the reote user.

**Comment by hazendaz** [comment] 2016-12-21 18:34
Do you know if springboot simply isnt using that field?  It sounds more like there issue since that comes from tomcat.  Maybe you can debug and see if any other data is availanle that has that info.  Also if possible can you write a little hello world app using spring boot with waffle?  It coukd end up helping us quite a bit and eventually make it to our demos once working.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bishnu-zwayam** [comment] 2016-12-22 06:13
Thanx for reply 
1)This is my project structure:
![project_structure](https://cloud.githubusercontent.com/assets/17123914/21416187/da6703ce-c836-11e6-95e8-6e4e6ec401c8.png)
2)web.xml
![web](https://cloud.githubusercontent.com/assets/17123914/21416760/77054a52-c83b-11e6-9547-f5b4bf1402ad.jpg)
3) pom.xml
![pom](https://cloud.githubusercontent.com/assets/17123914/21416768/7e8f84fe-c83b-11e6-8b58-621f2a90eabc.jpg)
4) controller
@RestController
@RequestMapping("/Waffle")
public class Waffle {
	
	@RequestMapping(value="/checkWaffle",method = RequestMethod.GET)
	public String checkWaffle(HttpServletRequest req){
		System.out.println(req.getRemoteUser()); // This is returning null
		return "success";
	}

}
5) Now when I make jar and run it and access http://localhost:9898/Waffle/checkWaffle , the remoteuser is showing null
Any help will be appreciated.
Thank you.

**Comment by hazendaz** [comment] 2016-12-27 03:34
Couple of things.  I"ve gotten this far in working now.  I didn't have everything you have there but figured most of it out.  So seems you are using older springboot setup and additionally using mixed versions of waffle.  Neither are a cause of the issue but something I wanted to point out.

Now, I think to get this working it will require a number of things potentially.  Please keep in mind I know next to nothing about spring boot so I'm simply guessing.

Things needed...

- TomcatEmbeddedServletContainerFactory needs configured for valve and realm.
- ApplicationSecurity needs setup with a number of things I believe from the configuration we show as examples for spring
- Waffle spring module is likely needed in this.

These are all guesses at the moment.  I've got this much coded up but still trying to figure it out and still getting null.  At the moment, when I get this going, it seems to skip the valve entirely.  I think that is exactly why it's null but still not completely clear what all needs to occur.  I'll make my code available on my fork under demo app (waffle-springboot).  Maybe that might help get it further or you might be able to assist back on what I'm doing to see if we can get this any closer.

**Comment by bishnu-zwayam** [comment] 2016-12-27 04:36
Thank you for your reply. I will try to do the things needed. It would be great if I get some information from your fork.

**Comment by hazendaz** [comment] 2016-12-27 05:17
@bishnu-zwayam 
Here is where I got to -> [here](https://github.com/hazendaz/waffle/commit/47d344d09dc875cc2cac936898288cd17d983a72)

At the moment, I couldn't get waffle to turn on and work so that is commented out in the Application class.  What you will see is just a call to super.  That will cause it to use spring default logon page.  There the user is simply 'user', and if you check the logback logs which land in the folder root, it will have a long string that will give you the password for that session.  Essentially that shows that 'user' does get into request.  So now it's just a matter of figuring this out.  I think I got as far as I could.  Hopefully you can bring more spring knowledge to assist.

**Comment by bishnu-zwayam** [comment] 2016-12-27 05:29
Ok I will use your code and try to take it further. And If you get something please let me know. Thank you.

**Comment by hazendaz** [comment] 2017-01-01 02:39
I moved this code over to a branch on my repo called 'springboot' so I can otherwise perform a release of the core code at this time.

**Comment by mgoldgeier** [comment] 2017-01-19 17:00
I have also been having problems getting Waffle to work with Spring Boot/Spring Security, but only when I use Internet Explorer as the browser. Chrome and Firefox seem to work OK though, so I'm not sure if the issue is the same as the one described here. I put together a very simple demo application that uses Spring Boot with Waffle. If I run this, sometimes it will work with IE and sometimes it will fail with:

`waffle.spring.NegotiateSecurityFilter    : error logging in user: com.sun.jna.platform.win32.Win32Exception: The token supplied to the function is invalid`

Perhaps someone could take a look and see if they can see the same issue?

The demo application is at: https://github.com/mgoldgeier/waffle-spring-boot-demo

**Comment by hazendaz** [comment] 2017-01-28 03:40
@mgoldgeier I went ahead and started watching your demo and forked it.  I don't have much time for next few months to work on waffle but wanted to keep tabs in case of progress of when I find time later on.  Thanks for making that available.

**Comment by r0n1am** [comment] 2017-02-15 02:17
@mgoldgeier I have the same problem too. Also if using Waffle 1.8.3 the app will fail miserably, but it is completely different problem.

**Comment by mgoldgeier** [comment] 2017-02-17 17:42
@r0n1am If that solves the problem, that would be great news. I haven't had a chance to look at it yet.

I don't understand why the code you mention would be necessary. Can you maybe explain what the difference would be and why/how NegotiateSecurityFilter would be getting called twice?

**Comment by r0n1am** [comment] 2017-02-17 18:24
@mgoldgeier I got the idea from [this post](http://stackoverflow.com/a/31571715) and followed comment to [this post](http://stackoverflow.com/a/37904857). 

Basically, [`NegotiateSecurityFilter`](https://github.com/Waffle/waffle/blob/master/Source/JNA/waffle-spring-security4/src/main/java/waffle/spring/NegotiateSecurityFilter.java) in `waffle-spring-security4` extends `GenericFilterBean` from Spring. When using Spring Boot, any GenericFilterBean in the context will be automatically added to the filter chain(actually all `Filter` [will be added](http://docs.spring.io/spring-boot/docs/1.4.3.RELEASE/reference/htmlsingle/#boot-features-embedded-container-servlets-filters-listeners-beans)). In the demo app, `addFilterBefore(negotiateSecurityFilter, BasicAuthenticationFilter.class);` in `SecurityConfig` added the filter to the filter chain again, which made the filter registered twice and called twice later on.

One interesting thing is that in my testing environment, Chrome and FireFox didn't have the problem and the filter seems work fine, i.e. showed correct information from AD. I don't know why only IE 11 have the problem (only tested IE11, don't know about other versions of IE or Edge).

I think the problem might be able to solve by rearrange those config classes in the demo app. But the solution provided in the StackoverFlow worked fine, so I didn't test it anymore.

**Comment by mgoldgeier** [comment] 2017-02-17 21:18
@r0n1am Awesome find! I did a real quick test and this did seem to fix the issue. At the very least, you were right that the filter was being registered twice. I also noticed that I had been only having issues with IE11, but not other browsers. I assume it comes down to a matter of timing differences between the browsers.

I updated the demo app with your fix.
I haven't touched Waffle 1.8.3, but it doesn't appear to have been released yet.

**Comment by hazendaz** [comment] 2017-12-18 01:45
Closing issue as this is completed on master.  Release of 1.9.0 is coming soon (most likely before christmas).

**Closed by hazendaz** 2017-12-18 01:45 UTC

**Comment by wussup** [comment] 2018-10-12 08:00
I still have the same ("The token supplied to the function is invalid") in IE and Edge :(

Classes SecurityConfig and WaffleConfig I got from https://github.com/mgoldgeier/waffle-spring-boot-demo

waffle-spring-security4 -> 1.9.1
Spring Boot -> 1.5.8.RELEASE

Logs:

```
2018-10-12 09:58:52.157 DEBUG 7192 --- [nio-8080-exec-3] o.s.b.w.f.OrderedRequestContextFilter    : Bound request context to thread: org.apache.catalina.connector.RequestFacade@58780f7c
2018-10-12 09:58:52.157 DEBUG 7192 --- [nio-8080-exec-3] o.s.security.web.FilterChainProxy        : /auth/ldap at position 1 of 12 in additional filter chain; firing Filter: 'WebAsyncManagerIntegrationFilter'
2018-10-12 09:58:52.157 DEBUG 7192 --- [nio-8080-exec-3] o.s.security.web.FilterChainProxy        : /auth/ldap at position 2 of 12 in additional filter chain; firing Filter: 'SecurityContextPersistenceFilter'
2018-10-12 09:58:52.157 DEBUG 7192 --- [nio-8080-exec-3] w.c.HttpSessionSecurityContextRepository : HttpSession returned null object for SPRING_SECURITY_CONTEXT
2018-10-12 09:58:52.157 DEBUG 7192 --- [nio-8080-exec-3] w.c.HttpSessionSecurityContextRepository : No SecurityContext was available from the HttpSession: org.apache.catalina.session.StandardSessionFacade@5f0b24f2. A new one will be created.
2018-10-12 09:58:52.158 DEBUG 7192 --- [nio-8080-exec-3] o.s.security.web.FilterChainProxy        : /auth/ldap at position 3 of 12 in additional filter chain; firing Filter: 'HeaderWriterFilter'
2018-10-12 09:58:52.158 DEBUG 7192 --- [nio-8080-exec-3] o.s.s.w.header.writers.HstsHeaderWriter  : Not injecting HSTS header since it did not match the requestMatcher org.springframework.security.web.header.writers.HstsHeaderWriter$SecureRequestMatcher@2f4c3c6e
2018-10-12 09:58:52.158 DEBUG 7192 --- [nio-8080-exec-3] o.s.security.web.FilterChainProxy        : /auth/ldap at position 4 of 12 in additional filter chain; firing Filter: 'LogoutFilter'
2018-10-12 09:58:52.158 DEBUG 7192 --- [nio-8080-exec-3] o.s.s.web.util.matcher.OrRequestMatcher  : Trying to match using Ant [pattern='/logout', GET]
2018-10-12 09:58:52.158 DEBUG 7192 --- [nio-8080-exec-3] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/auth/ldap'; against '/logout'
2018-10-12 09:58:52.158 DEBUG 7192 --- [nio-8080-exec-3] o.s.s.web.util.matcher.OrRequestMatcher  : Trying to match using Ant [pattern='/logout', POST]
2018-10-12 09:58:52.158 DEBUG 7192 --- [nio-8080-exec-3] o.s.s.w.u.matcher.AntPathRequestMatcher  : Request 'GET /auth/ldap' doesn't match 'POST /logout
2018-10-12 09:58:52.158 DEBUG 7192 --- [nio-8080-exec-3] o.s.s.web.util.matcher.OrRequestMatcher  : Trying to match using Ant [pattern='/logout', PUT]
2018-10-12 09:58:52.158 DEBUG 7192 --- [nio-8080-exec-3] o.s.s.w.u.matcher.AntPathRequestMatcher  : Request 'GET /auth/ldap' doesn't match 'PUT /logout
2018-10-12 09:58:52.158 DEBUG 7192 --- [nio-8080-exec-3] o.s.s.web.util.matcher.OrRequestMatcher  : Trying to match using Ant [pattern='/logout', DELETE]
2018-10-12 09:58:52.158 DEBUG 7192 --- [nio-8080-exec-3] o.s.s.w.u.matcher.AntPathRequestMatcher  : Request 'GET /auth/ldap' doesn't match 'DELETE /logout
2018-10-12 09:58:52.158 DEBUG 7192 --- [nio-8080-exec-3] o.s.s.web.util.matcher.OrRequestMatcher  : No matches found
2018-10-12 09:58:52.158 DEBUG 7192 --- [nio-8080-exec-3] o.s.security.web.FilterChainProxy        : /auth/ldap at position 5 of 12 in additional filter chain; firing Filter: 'NegotiateSecurityFilter'
2018-10-12 09:58:52.158 DEBUG 7192 --- [nio-8080-exec-3] waffle.spring.NegotiateSecurityFilter    : GET /uemserver/auth/ldap, contentlength: -1
2018-10-12 09:58:52.158 DEBUG 7192 --- [nio-8080-exec-3] w.s.spi.NegotiateSecurityFilterProvider  : security package: Negotiate, connection id: 0:0:0:0:0:0:0:1:53731
2018-10-12 09:58:52.158 DEBUG 7192 --- [nio-8080-exec-3] w.s.spi.NegotiateSecurityFilterProvider  : token buffer: 1632 byte(s)
2018-10-12 09:58:52.160 DEBUG 7192 --- [nio-8080-exec-3] w.s.spi.NegotiateSecurityFilterProvider  : continue token: oYGHMIGEoAMKAQGhCwYJKoZIgvcSAQIConAEbmBsBgkqhkiG9xIBAgIDAH5dMFugAwIBBaEDAgEepBEYDzIwMTgxMDEyMDc1ODUyWqUFAgMJ8+GmAwIBKakNGwtCWk1XLkdPVi5QTKohMB+gAwIBAaEYMBYbFHN2Yy5iZ2lrX3VlbS1zZXJ2aWNl
2018-10-12 09:58:52.160 DEBUG 7192 --- [nio-8080-exec-3] w.s.spi.NegotiateSecurityFilterProvider  : continue required: true
2018-10-12 09:58:52.160 DEBUG 7192 --- [nio-8080-exec-3] w.c.HttpSessionSecurityContextRepository : SecurityContext is empty or contents are anonymous - context will not be stored in HttpSession.
2018-10-12 09:58:52.160 DEBUG 7192 --- [nio-8080-exec-3] s.s.w.c.SecurityContextPersistenceFilter : SecurityContextHolder now cleared, as request processing completed
2018-10-12 09:58:52.160 DEBUG 7192 --- [nio-8080-exec-3] o.s.b.w.f.OrderedRequestContextFilter    : Cleared thread-bound request context: org.apache.catalina.connector.RequestFacade@58780f7c
2018-10-12 09:58:52.169 DEBUG 7192 --- [nio-8080-exec-5] o.s.b.w.f.OrderedRequestContextFilter    : Bound request context to thread: org.apache.catalina.connector.RequestFacade@58780f7c
2018-10-12 09:58:52.169 DEBUG 7192 --- [nio-8080-exec-5] o.s.security.web.FilterChainProxy        : /auth/ldap at position 1 of 12 in additional filter chain; firing Filter: 'WebAsyncManagerIntegrationFilter'
2018-10-12 09:58:52.169 DEBUG 7192 --- [nio-8080-exec-5] o.s.security.web.FilterChainProxy        : /auth/ldap at position 2 of 12 in additional filter chain; firing Filter: 'SecurityContextPersistenceFilter'
2018-10-12 09:58:52.169 DEBUG 7192 --- [nio-8080-exec-5] w.c.HttpSessionSecurityContextRepository : HttpSession returned null object for SPRING_SECURITY_CONTEXT
2018-10-12 09:58:52.169 DEBUG 7192 --- [nio-8080-exec-5] w.c.HttpSessionSecurityContextRepository : No SecurityContext was available from the HttpSession: org.apache.catalina.session.StandardSessionFacade@5f0b24f2. A new one will be created.
2018-10-12 09:58:52.169 DEBUG 7192 --- [nio-8080-exec-5] o.s.security.web.FilterChainProxy        : /auth/ldap at position 3 of 12 in additional filter chain; firing Filter: 'HeaderWriterFilter'
2018-10-12 09:58:52.170 DEBUG 7192 --- [nio-8080-exec-5] o.s.s.w.header.writers.HstsHeaderWriter  : Not injecting HSTS header since it did not match the requestMatcher org.springframework.security.web.header.writers.HstsHeaderWriter$SecureRequestMatcher@2f4c3c6e
2018-10-12 09:58:52.170 DEBUG 7192 --- [nio-8080-exec-5] o.s.security.web.FilterChainProxy        : /auth/ldap at position 4 of 12 in additional filter chain; firing Filter: 'LogoutFilter'
2018-10-12 09:58:52.170 DEBUG 7192 --- [nio-8080-exec-5] o.s.s.web.util.matcher.OrRequestMatcher  : Trying to match using Ant [pattern='/logout', GET]
2018-10-12 09:58:52.170 DEBUG 7192 --- [nio-8080-exec-5] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/auth/ldap'; against '/logout'
2018-10-12 09:58:52.170 DEBUG 7192 --- [nio-8080-exec-5] o.s.s.web.util.matcher.OrRequestMatcher  : Trying to match using Ant [pattern='/logout', POST]
2018-10-12 09:58:52.170 DEBUG 7192 --- [nio-8080-exec-5] o.s.s.w.u.matcher.AntPathRequestMatcher  : Request 'GET /auth/ldap' doesn't match 'POST /logout
2018-10-12 09:58:52.170 DEBUG 7192 --- [nio-8080-exec-5] o.s.s.web.util.matcher.OrRequestMatcher  : Trying to match using Ant [pattern='/logout', PUT]
2018-10-12 09:58:52.170 DEBUG 7192 --- [nio-8080-exec-5] o.s.s.w.u.matcher.AntPathRequestMatcher  : Request 'GET /auth/ldap' doesn't match 'PUT /logout
2018-10-12 09:58:52.170 DEBUG 7192 --- [nio-8080-exec-5] o.s.s.web.util.matcher.OrRequestMatcher  : Trying to match using Ant [pattern='/logout', DELETE]
2018-10-12 09:58:52.170 DEBUG 7192 --- [nio-8080-exec-5] o.s.s.w.u.matcher.AntPathRequestMatcher  : Request 'GET /auth/ldap' doesn't match 'DELETE /logout
2018-10-12 09:58:52.170 DEBUG 7192 --- [nio-8080-exec-5] o.s.s.web.util.matcher.OrRequestMatcher  : No matches found
2018-10-12 09:58:52.170 DEBUG 7192 --- [nio-8080-exec-5] o.s.security.web.FilterChainProxy        : /auth/ldap at position 5 of 12 in additional filter chain; firing Filter: 'NegotiateSecurityFilter'
2018-10-12 09:58:52.170 DEBUG 7192 --- [nio-8080-exec-5] waffle.spring.NegotiateSecurityFilter    : GET /uemserver/auth/ldap, contentlength: -1
2018-10-12 09:58:52.170 DEBUG 7192 --- [nio-8080-exec-5] w.s.spi.NegotiateSecurityFilterProvider  : security package: Negotiate, connection id: 0:0:0:0:0:0:0:1:53731
2018-10-12 09:58:52.170 DEBUG 7192 --- [nio-8080-exec-5] w.s.spi.NegotiateSecurityFilterProvider  : token buffer: 1575 byte(s)
2018-10-12 09:58:52.173 DEBUG 7192 --- [nio-8080-exec-5] w.s.spi.NegotiateSecurityFilterProvider  : continue token: oXkwd6ADCgEBonAEbmBsBgkqhkiG9xIBAgIDAH5dMFugAwIBBaEDAgEepBEYDzIwMTgxMDEyMDc1ODUyWqUFAgMKKpKmAwIBKakNGwtCWk1XLkdPVi5QTKohMB+gAwIBAaEYMBYbFHN2Yy5iZ2lrX3VlbS1zZXJ2aWNl
2018-10-12 09:58:52.173 DEBUG 7192 --- [nio-8080-exec-5] w.s.spi.NegotiateSecurityFilterProvider  : continue required: true
2018-10-12 09:58:52.173 DEBUG 7192 --- [nio-8080-exec-5] w.c.HttpSessionSecurityContextRepository : SecurityContext is empty or contents are anonymous - context will not be stored in HttpSession.
2018-10-12 09:58:52.175 DEBUG 7192 --- [nio-8080-exec-5] s.s.w.c.SecurityContextPersistenceFilter : SecurityContextHolder now cleared, as request processing completed
2018-10-12 09:58:52.175 DEBUG 7192 --- [nio-8080-exec-5] o.s.b.w.f.OrderedRequestContextFilter    : Cleared thread-bound request context: org.apache.catalina.connector.RequestFacade@58780f7c
```

**Comment by hazendaz** [comment] 2018-10-12 11:40
Have you tried this with the waffle spring boot module?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by wussup** [comment] 2018-10-12 11:46
@hazendaz Do you meen waffle-spring-boot-starter?

**Comment by hazendaz** [comment] 2018-10-12 11:49
Yes

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by wussup** [comment] 2018-10-12 12:00
@hazendaz Same error :(

Already tried to update Spring Boot version to 2.0.5, but nothing changed

**Comment by hazendaz** [comment] 2018-10-25 11:00
Great! Glad to here it's working now.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by wussup** [comment] 2018-10-26 08:49
@hazendaz Do you have any solution for Mixed Authentication with Spring Boot and Waffle?

I mean, that I would like to login with Waffle SSO for Intranet users and I would like to login with Login Form for Internet users without showing Waffle domain login window, but only mine window.

**Comment by wussup** [comment] 2018-10-26 11:28
> @hazendaz Do you have any solution for Mixed Authentication with Spring Boot and Waffle?
> 
> I mean, that I would like to login with Waffle SSO for Intranet users and I would like to login with Login Form for Internet users without showing browser popup, but only my login page.

I solved it by extending NegotiateSecurityFilterEntryPoint, method _commence_ now look like:

```
@Override
public void commence(final HttpServletRequest request, final HttpServletResponse response,
		final AuthenticationException authException) throws IOException, ServletException {
	if (isInternetIP(request)) {
		// Authentication failed, send error response.
		response.setStatus(HttpServletResponse.SC_UNAUTHORIZED);

		PrintWriter writer = response.getWriter();
		writer.println("HTTP Status 401: " + authException.getMessage());
	} else {
		super.commence(request, response, authException);
	}

}
```

Do you know any better solution?

**Comment by hazendaz** [comment] 2018-10-26 11:54
In your situation, having a filter like you do is your best option.  I've seen the done in similar ways to catch and direct logins as needed.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
