### ISSUE TITLE
Not enough system resources to execute the required services

### ISSUE THREAD

**Issue by ngtruongan** [Waffle/waffle#241] opened 2015-09-10 06:42 UTC
Hi,

In our test system (Tomcat 8), sometimes the following exception is thrown, and I must restart the system.

```
com.sun.jna.platform.win32.Win32Exception: Not enough system resources to execute the required services.
    at com.sun.jna.platform.win32.Advapi32Util.getAccountBySid(Advapi32Util.java:229)
    at com.sun.jna.platform.win32.Advapi32Util.getAccountBySid(Advapi32Util.java:203)
    at com.sun.jna.platform.win32.Advapi32Util.getTokenAccount(Advapi32Util.java:427)
    at waffle.windows.auth.impl.WindowsIdentityImpl.getWindowsAccount(WindowsIdentityImpl.java:46)
    at waffle.windows.auth.impl.WindowsIdentityImpl.getFqn(WindowsIdentityImpl.java:60)
    at waffle.servlet.WindowsPrincipal.<init>(WindowsPrincipal.java:68)
    at de.elo.ix.auth.NegoSecurityFilter.doFilter(NegoSecurityFilter.java:239)
    at de.elo.ix.webdav.WAuthenticateFilter.doFilter(WAuthenticateFilter.java:47)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at net.java.dev.webdav.interop.WindowsRedirectorPatchResourceFilter.doFilter(WindowsRedirectorPatchResourceFilter.java:138)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
    at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2441)
    at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2430)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
```

Regards

**Comment by hazendaz** [comment] 2015-09-11 01:39
This might be related to a handler leak that was just discovered and fixed.  Can you pull the latest source and build it then see if that solves your issue?

**Comment by dblock** [comment] 2016-04-04 12:07
Bump @ngtruongan.

**Comment by ngtruongan** [comment] 2016-10-10 14:18
Hi,
I still have this problem. I'm using Waffle 1.7.

**Comment by hazendaz** [comment] 2016-10-10 14:32
Can you try version 1.8.1?

Get Outlook for Android<https://aka.ms/ghei36>



On Mon, Oct 10, 2016 at 10:18 AM -0400, "ngtruongan" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
I still have this problem. I'm using Waffle 1.7.

-

**Comment by hazendaz** [comment] 2017-02-11 18:29
What are you memory settings?  Java version?

**Comment by ngtruongan** [comment] 2017-02-14 10:02
Hi,

Java 1.8.0_91-b60
Apache Tomcat/7.0.52
-XX:MaxPermSize=200m
Initial memory pool 1000 MB
Maximum memory pool 2000 MB

**Comment by hazendaz** [comment] 2017-02-15 04:09
still not quite sure what the issue is.  However, since you are on java 8, remove the -XX:MaxPermSize.  There is no such thing in java 8.  That was removed.  You should be getting warnings about that setting.  Otherwise I don't see what would be causing your issue.  If you can go over to our user group and ask the same questions with the same given information.  More people are available there that might have seen this and have a solution.  You might want to try waffle 1.8.2 or 1.8.3.  And definitely read through docs in case something jumps out.  Also would suggest using one of our demos to see if those are encountering same issues.

**Comment by hazendaz** [comment] 2022-06-26 23:50
closing as really old and no follow up.  not likely an issue.

**Closed by hazendaz** 2022-06-26 23:50 UTC
Labels: bug?
